### ISSUE TITLE
No list names are created by default on first-run

### ISSUE THREAD

**Issue by PCOWandre** [GregTheMadMonk/noaftodo#2]
Which breaks formatting in the application. The columns don't line up with the head row unless a name is defined. This should happen by default when a fresh data file is written.

**Comment by GregTheMadMonk** [comment]
Nah, list names shouldn't be created by default. The problem was a stupid mistake in the list column definition. Should be fixed in the last commit (just to be sure, I let you close the issue if it works on your end).

**Comment by GregTheMadMonk** [comment]
As you seem to have no further complaints on this, the issue is closed.
