### ISSUE TITLE
Compiling (make) not working as expected

### ISSUE THREAD

**Issue by pjlinden** [GregTheMadMonk/noaftodo#3]
Hello,

After cloning noaftodo I go into the noaftodo-dir and, as instructed, use the command 'make'.
I get the following error-message:

Compiling obj/noaftodo_list.o...
g++ -fpermissive -c -o obj/noaftodo_list.o src/noaftodo_list.cpp
Compiling obj/noaftodo_cui.o...
g++ -fpermissive -c -o obj/noaftodo_cui.o src/noaftodo_cui.cpp
src/noaftodo_cui.cpp:7:10: fatal error: curses.h: No such file or directory
    7 | #include <curses.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:43: obj/noaftodo_cui.o] Error 1

Do I have to install any other program to make 'make' work? (curses.h)
Thank you.
Jan

**Comment by GregTheMadMonk** [comment]
Hello!
Yeah, you need to install a package that provides it. It would be `libncurses5-dev` on a Debian-based or just `ncurses` on an Arch-based distros, I believe. Not sure about others, but I'm it' would be no problem for you to figure out.
I probably should give more instructions about building :)
Hope it works for you!

**Comment by GregTheMadMonk** [comment]
I will be closing the issue in a week if there's no reply from you, but you're still welcome to comment here at any time if you have more problems.

**Comment by pjlinden** [comment]
Hi Greg,
I did sent a e-mail, but apparently it did not reach you.

After installing libncurses5-dev it all worked great.
Thank you!
Greetings,
Jan

**Comment by GregTheMadMonk** [comment]
Hmm, weird...
Anyways, you're welcome!
